//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_MVC_PB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PHONEBOOKEntities : DbContext
    {
        public DB_PHONEBOOKEntities()
            : base("name=DB_PHONEBOOKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhoneBook> PhoneBooks { get; set; }

        public System.Data.Entity.DbSet<WEBAPI_MVC_PB.Models.PhoneBookClass> PhoneBookClasses { get; set; }
    }
}
